# Q12.
```{admonition}
:class: note
This problem involves simple linear regression without an intercept.

In [1]:
import numpy as np
import statsmodels.api as sm
from ISLP.models import summarize

## (a)
```{admonition}
:class: note
Recall that the coefficient estimate $\hat{\beta}$ for the linear regression of $Y$ onto $X$ without an intercept is given by $$\hat{\beta} = \frac{\sum_{i=1}^{n}x_{i}y_{i}}{\sum_{i=1}^{n}x_{i}^{2}}.$$ Under what circumstance is the coefficient estimate for the regression of $X$ onto $Y$ the same as the coefficient estimate for the regression of $Y$ onto $X$?

When the sum of squares of the $x_{i}$ is equal to the sum of squares of the $y_{i}$.

## (b)
```{admonition}
:class: note
Generate an example in `Python` with $n = 100$ observations in which the coefficient estimate for the regression of $X$ onto $Y$ is *different* from the coefficient estimate for the regression of $Y$ onto $X$.

In [2]:
rng = np.random.default_rng(1728)
n = 100
x1 = rng.normal(size = n)
y1 = 3*x1+rng.normal(size = n)

In [3]:
model1 = sm.OLS(y1,x1).fit()
summarize(model1)

      coef  std err       t  P>|t|
x1  2.9507    0.086  34.288    0.0

In [4]:
model2 = sm.OLS(x1,y1).fit()
summarize(model2)

      coef  std err       t  P>|t|
x1  0.3126    0.009  34.288    0.0

## (c)
```{admonition}
:class: note
Generate an example in `Python` with $n = 100$ observations in which the coefficient estimate for the regression of $X$ onto $Y$ is *the same as* from the coefficient estimate for the regression of $Y$ onto $X$.

In [5]:
x2 = rng.normal(size = n)
y2 = 0.75*x2[:n-1]+rng.normal(scale = 0.25, size = n-1)
y2 = np.append(y2,np.sqrt((x2**2).sum()-(y2**2).sum()))

In [6]:
model3 = sm.OLS(y2,x2).fit()
summarize(model3)

      coef  std err      t  P>|t|
x1  0.6786    0.074  9.193    0.0

In [7]:
model4 = sm.OLS(x2,y2).fit()
summarize(model4)

      coef  std err      t  P>|t|
x1  0.6786    0.074  9.193    0.0