# Q7.
This problem makes use of the `Carseats` dataset.

In [2]:
import numpy as np
import pandas as pd

In [3]:
import statsmodels.api as sm

In [ ]:
carseats = pd.read_csv('../../../ALL CSV FILES - 2nd Edition/Carseats.csv')

In [5]:
carseats.sample(3)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
122,6.88,119,100,5,45,108,Medium,75,10,Yes,Yes
13,10.96,115,28,11,29,86,Good,53,18,Yes,Yes
361,8.68,131,25,10,183,104,Medium,56,15,No,Yes

In [6]:
carseats.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc          str
Age              int64
Education        int64
Urban              str
US                 str
dtype: object

## (a)
```{admonition}
:class: note
For each quantitative variable in the dataset besides `Sales`, fit a linear model to predict `Sales` using that quantitative variable. Report the $p$-values associated with the coefficients for the variables.

In [7]:
num_var = carseats.select_dtypes(include=['int64']).columns

In [8]:
pvals = {}
for var in num_var:
    data = sm.add_constant(carseats[var])
    model = sm.OLS(carseats['Sales'],data).fit()
    pvals[var] = model.pvalues[var]
pval_raw = pd.DataFrame.from_dict(pvals,orient='index',columns=['p'])

In [9]:
pval_raw

                        p
CompPrice    2.009398e-01
Income       2.309670e-03
Advertising  4.377677e-08
Population   3.139816e-01
Price        7.618187e-21
Age          2.788950e-06
Education    2.999442e-01

## (b)
```{admonition}
:class: note
Suppose we control the Type I error at level $\alpha = 0.05$ for the $p$-values obtained in (a). Which null hypotheses do we reject?

In [10]:
pval_raw[pval_raw['p']<0.05]

                        p
Income       2.309670e-03
Advertising  4.377677e-08
Price        7.618187e-21
Age          2.788950e-06

## (c)
```{admonition}
:class: note
Now suppose we control the FWER at level $0.05$ for the $p$-values. Which null hypotheses do we reject?

In [11]:
bonf_bool = sm.stats.multipletests(pval_raw['p'],alpha=0.05,method='bonferroni')[0]
pval_raw.loc[bonf_bool]

                        p
Income       2.309670e-03
Advertising  4.377677e-08
Price        7.618187e-21
Age          2.788950e-06

In [12]:
holm_bool = sm.stats.multipletests(pval_raw['p'],alpha=0.05,method='holm')[0]
pval_raw.loc[holm_bool]

                        p
Income       2.309670e-03
Advertising  4.377677e-08
Price        7.618187e-21
Age          2.788950e-06

## (d)
```{admonition}
:class: note
Finally, suppose we control the FDR at level $0.2$ for the $p$-values. Which null hypotheses do we reject?

In [13]:
fdr_bool = sm.stats.multipletests(pval_raw['p'],alpha=0.2,method='fdr_bh')[0]
pval_raw.loc[fdr_bool]

                        p
Income       2.309670e-03
Advertising  4.377677e-08
Price        7.618187e-21
Age          2.788950e-06